#coding=utf-8

import unittest

from CalAdd import AddTest
from CalMultiplicative import MltiplicativeTest

import HTMLTestRunner

if __name__ == '__main__':

    suite = unittest.TestSuite()
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(AddTest))
    suite.addTest(unittest.TestLoader().loadTestsFromTestCase(MltiplicativeTest))

    with open('HTMLTestRunner', 'wb') as f:
        runner = HTMLTestRunner.HTMLTestRunner(stream=f,
        title='CalFunc Test Report',
        description='generated by HTMLTestRunner.',
        verbosity=2
        )
        runner.run(suite)

    


